library(RRtools)
library(dartR)
library(dplyr)
library(diveRsity)
library(data.table)
library(LEA)
library(mapplots)


devtools::source_url("https://github.com/eilishmcmaster/SoS_functions/blob/main/sos_functions.R?raw=TRUE")
devtools::source_url("https://github.com/eilishmcmaster/SoS_functions/blob/main/kin_compare_functions.R?raw=TRUE")


###note that this loads scripts generated by SY to automate / make RnR summary reports from DArTseq data. Should probably be put onto Git#####
load("PSFsaved_scripts4autom2.RData")

#####Set up needed variables#####
maindir <- '/Users/eilishmcmaster/Documents/ReCER_base_analysis_pipeline/'

setwd(maindir)
#Number of analysis columns in metafile
Num_analyses <- 3
#Analysis column in meta file you want to run
analysis.index <- 1
#Minimum number of samples to keep a population in analyses
Minimum_pop <- 5
#Kinship threshold to considered samples as belonging to a single genet
Clonal_threshold <- 0.4
#Number of samples to subsample populations to prior to analyses
samples_per_pop <- 5

#Load data and quality filter loci and samples
d1        <- new.read.dart.xls.onerow(RandRbase,species,dataset,topskip, euchits=FALSE, altcount=TRUE)
qc1       <- report.dart.qc.stats(d1, RandRbase, species, dataset, threshold_missing_loci = 0.8)

d2        <- remove.poor.quality.snps(d1, min_repro=0.96, max_missing=0.2)
qc2       <- report.dart.qc.stats(d2, RandRbase, species, dataset)

d3        <- sample.one.snp.per.locus.random(d2, seed=214241)
qc3       <- report.dart.qc.stats(d3, RandRbase, species, dataset)

#Load meat data and attach to dart data
m1        <- read.meta.data.new(d3, RandRbase, species, dataset)

write.table(data.frame(sample=d3$sample_names[!(d3$sample_names %in% m1$sample_names)]), 
            paste0(species,"/samples_in_dart_not_in_meta.tsv"), sep="\t", row.names = FALSE)

dm        <- dart.meta.data.merge(d3, m1)

analysis <-  colnames(m1$analyses)[analysis.index]
fields    <- c(analysis)
dms     <- data.by.meta.fields(dm, fields, RandRbase, species, dataset, object = analysis)

#####Check for clonal samples and choose only sample with lowest missingness per genet#####
#dms <- remove_clones(dms,RandRbase,species,dataset,analysis.index,maf=0.1, mis=0.2,Clonal_threshold)

#####Remove populations with less than five samples#####
dms <- remove_by_sample_number(dms,analysis.index)

#####Subsamples populations down to a standard number of samples (change value in third line to change target value)######
dms <- subsample_sites(dms,analysis,samples_per_pop)

####Remove sites based upon geographic proximity#####
#dms <- remove_by_site_proximity(dms,analysis.index)

#correct inconsistencies in J's scripts for naming treatment which is for naming files
treatment <- paste0("raw_SNPFilt_1SNPperClone_Field_", analysis)
dms$treatment <- treatment

###############################Splitstree################################################################################
# snp <- dart2splitstree(dms, RandRbase, species, dataset,  dms$meta$analyses[,analysis], add_pop=TRUE)
#output nexus file will be in main directory after RandRbase

###########################################PCA########################################
nd_gl  <- dart2gl(dms, RandRbase, species, dataset)
nd_gl <- gl.compliance.check(nd_gl)
nd_pca <- gl.pcoa(nd_gl, nf = 5, parallel = FALSE)

PCA_plots(nd_pca)

###########################################FST########################################
#generate pairwise fst for populations
#determine if IBD is significant - Mantel test
pFst      <- population.pw.Fst(dms, dms$meta$analyses[,analysis], RandRbase,species,dataset) #calculates genetic distance between populations
pS        <- population.pw.spatial.dist(dms, dms$meta$analyses[,analysis]) #calculates geographic distance between populations

fst_plots(pFst, pS)
#script generate IBD plot and heatmaps

###########################################LEA########################################
kvalrange <- 1:25
real_kvalrange <- 2:8

##check for LEA FOLDER
lea_popdir <- paste0(RandRbase,species,"/popgen/",treatment,"/lea/")
if (!dir.exists(lea_popdir)) {
  nd_lea <- dart2lea(dms, RandRbase, species, dataset)
  snmf1=snmf(nd_lea, K=kvalrange, entropy = TRUE, repetitions = 1, project = "new")
  plot(snmf1, lwd = 6, col = "red", pch=1)
  LEA_plots(dms, outputloc, nd_lea,treatment, dataset, species)
} else {
  print("remove LEA folder under popgen folder first!!!")
  #or if you have already run LEA, and just want to replot everything?
  nd_lea <- dart2lea(dms, RandRbase, species, dataset)
  LEA_plots(dms, outputloc, nd_lea,treatment, dataset, species)
}

#######################################DIVERSITY######################################
gp   <- dart2genepop(dms, RandRbase, species, dataset, dms$meta$analyses[,analysis],maf_val=0.01)
bs <- basicStats(infile = gp, outfile = NULL,
                 fis_ci = FALSE, ar_ci = TRUE,
                 ar_boots = 999,
                 rarefaction = FALSE, ar_alpha = 0.05)
diversity_plots(bs)

#####################################SUMMARISE DART DATA####################################
summarise_QC(species, RandRbase, dataset)
combine_plots(species)
