library(patchwork)
library(gridExtra)
library(RColorBrewer)
library(circlize) 
library(scatterpie)
library(tanggle)
library(RSplitsTree)
library(ggmap)
library(lubridate)
library(ggplot2)
library(dplyr)
library(data.table)
library(ggrepel)
library(tidyverse)
library(ggsn)
library(ggspatial)
library(readxl)
library(heatmaply)
library(circlize)
library(ComplexHeatmap)
library(igraph)
library(SNPRelate)
library(geosphere)
library(reshape2)
library(vegan)
library(ggforce)
library(openxlsx)
library(stringr)
library(pracma)
library(ggpubr)
library(RRtools)
library(ggthemes)
library(RColorBrewer)
library(ozmaps)
library(adegenet)
library(tidyr)
library("viridis")
library(diveRsity)
library(RRtools)


maindir <- '/Users/eilishmcmaster/Documents/ReCER_base_analysis_pipeline/'

setwd(maindir)

setup_variables <- read.xlsx("0_setup_variables.xlsx", colNames = TRUE)
species <- setup_variables[1,2]
dataset <- setup_variables[2, 2]
RandRbase <- ""
raw_meta_path <- setup_variables[3, 2]

topskip   <- 6
nmetavar  <- 18
missingness <- 0.3

species_col_name <- setup_variables[4, 2]
site_col_name <- setup_variables[5, 2] # this is the equivalent of analysis


#Number of analysis columns in metafile
Num_analyses <- 3
#Analysis column in meta file you want to run
analysis.index <- 1
#Minimum number of samples to keep a population in analyses
Minimum_pop <- 5
#Kinship threshold to considered samples as belonging to a single genet
Clonal_threshold <- 0.4
#Number of samples to subsample populations to prior to analyses
samples_per_pop <- 5


devtools::source_url("https://github.com/eilishmcmaster/SoS_functions/blob/main/sos_functions.R?raw=TRUE")
# devtools::source_url("https://github.com/eilishmcmaster/SoS_functions/blob/main/kin_compare_functions.R?raw=TRUE")
###note that this loads scripts generated by SY to automate / make RnR summary reports from DArTseq data. Should probably be put onto Git#####
load("PSFsaved_scripts4autom2.RData")

#### Import and QC ####

#Load data and quality filter loci and samples
d1        <- new.read.dart.xls.onerow(RandRbase,species,dataset,topskip, euchits=FALSE, altcount=TRUE)
qc1       <- report.dart.qc.stats(d1, RandRbase, species, dataset, threshold_missing_loci = 0.8)

d2        <- remove.poor.quality.snps(d1, min_repro=0.96, max_missing=0.2)
qc2       <- report.dart.qc.stats(d2, RandRbase, species, dataset)

d3        <- sample.one.snp.per.locus.random(d2, seed=214241)
qc3       <- report.dart.qc.stats(d3, RandRbase, species, dataset)

#Load meta data and attach to dart data
m1        <- read.meta.data.full.analyses.df(d3, RandRbase, species, dataset)
# m2 <- custom.read(species, dataset) %>% .[which(.$sample %in% m1$sample_names),]

write.table(data.frame(sample=d3$sample_names[!(d3$sample_names %in% m1$sample_names)]), 
            paste0(species,"/outputs/tables/samples_in_dart_not_in_meta.tsv"), sep="\t", row.names = FALSE)

dm        <- dart.meta.data.merge(d3, m1)

# remove samples that are NA for site variable 
samples_with_site_variable <- dm$sample_names[!is.na(dm$meta$analyses[,site_col_name])]
dms <- remove.by.list(dm, samples_with_site_variable)

treatment <- dms$treatment
# get mean values of lat and long per species site 

# # Original Site Summary
original_site_summary <- dms$meta$analyses %>% as.data.frame()%>%
  group_by(!!sym(species_col_name), !!sym(site_col_name)) %>%
  summarize(n_original = sum(n()),
            lat = mean(as.numeric(lat), na.rm=TRUE),
            long = mean(as.numeric(long),na.rm=TRUE),
            .groups = 'drop') %>%
  filter(n_original > 0) %>%
  as.data.frame()

divxlims <- c(min(original_site_summary$long, na.rm=TRUE)-0.2,max(original_site_summary$long, na.rm=TRUE)+0.2) #find the min / max longitude
divylims <- c(min(original_site_summary$lat, na.rm=TRUE)-0.2,max(original_site_summary$lat, na.rm=TRUE)+0.2) #find the min / max latitude

# make dms where there are no n=1 site
not_n1_sites <- as.vector(original_site_summary[original_site_summary$n_original<=1,2]) #remove groups where n<=1
not_n1_samples <- dms$sample_names[which(!(dms$meta$analyses[,site_col_name] %in% not_n1_sites))]
dms_no_n1_sites <- remove.by.list(dms, not_n1_samples)

# #######!!!!!!!!!!!!!!!!!!!!!! make conditional 
# #####Remove populations with less than five samples#####
# dms <- remove_by_sample_number(dms,analysis.index)
# 
# #####Subsamples populations down to a standard number of samples (change value in third line to change target value)######
# dms <- subsample_sites(dms,analysis,samples_per_pop)
# #######!!!!!!!!!!!!!!!!!!!!!! make conditional 


#### Colour palettes #### 
sp_colours <- named_list_maker(dms$meta$analyses[,species_col_name], "Spectral", 9)

sp_shapes <- 1:length(unique(dms$meta$analyses[,species_col_name]))
names(sp_shapes) <- unique(dms$meta$analyses[,species_col_name])

# get sites in order
site_categories <- unique(dms$meta$analyses[,site_col_name])
site_categories <- site_categories[site_categories!="no_geo_data"]
site_categories <- site_categories[order(as.numeric(site_categories))]

site_colours <- named_list_maker(site_categories, "Set3", 12)
site_colours <- c(site_colours, "no_geo_data"="grey30")

site_shapes <- rep(1:25, length.out = length(unique(dms$meta$analyses[,site_col_name])))
names(site_shapes) <- unique(dms$meta$analyses[,site_col_name])

site_order <- names(site_colours)
#### clones ####
# find and remove clones using SNPrelate kinship 

#calculate kinship by population 
# VERY important that the population groups are true genetic groups and not conglomerates of multiple genetic groups
# this can be species, subpops, or sites 
kin <- individual_kinship_by_pop(dms, RandRbase, species, dataset, dms$meta$analyses[,species_col_name], maf=0.1, mis=0.2, as_bigmat=TRUE)

# Finding the clones
#https://kateto.net/netscix2016.html
kin2 <- as.data.frame(kin) %>%mutate_all(~replace(.,.<=0.4, 0)) #VERY IMPORTANT, removes all of the pairwise connections that are k<0.45 
diag(kin2) <- 0
kin3 <- kin2

kin3<- as.data.frame(kin3) %>%mutate_all(~replace(.,.>0, 1)) # replaces all remaining pairwise connections with 1 (all are equal above k>0.45)

# cluster the clones 
network <- graph_from_adjacency_matrix(as.matrix(kin3), mode="undirected", diag=F,weighted=T) #makes the network based on k>0.45 
plot(network)

ceb <- cluster_fast_greedy(network) # makes cluster groupings

#visualise groups
plot(ceb, network, vertex.label.color="transparent", vertex.size=2, edge.width=0.4) #make the network plot

# get clones 
clones <-as.data.frame(cbind(genet=ceb$membership, sample=ceb$names)) #get the clones from the network as a df
clones_out <- merge(clones, dms$meta$analyses[,c("sample","lat","long",site_col_name,species_col_name)], by="sample") #add some metadata
clones_out <- clones_out[order(as.numeric(clones_out$genet)),] #order the table by genet 
clones_out$genet <- as.numeric(clones_out$genet)

# Export data if you want 
# write.table(clones_out, paste0(species,"/outputs/clones_out.tsv"), sep="\t", row.names=FALSE, col.names=TRUE)
clones_out
write.xlsx(clones_out, paste0(species,"/outputs/tables/clones.xlsx"), asTable = FALSE, overwrite = TRUE)

# 
# # Remove duplicate clones from working data
# #close clones with highest quality data (least missingess)
# missingness_gt <- as.data.frame(rowSums(is.na(dms[["gt"]]))/ncol(dms[["gt"]])) #get missingness of all samples
# colnames(missingness_gt) <- "missingness"
# clone_missing <- merge(clones_out, missingness_gt, by.x="sample", by.y=0) # merge the clone data
# clone_missing <- clone_missing[order(clone_missing$missingness),] #order by missingness low to high
# 
# unique_genets <- distinct(clone_missing, genet, .keep_all=TRUE) #keeps the top result for each genet (lowest missingness)
# 
# #make a list removing duplicate clones
# non_clones <- dms$sample_names[which(!dms$sample_names %in% clones_out$sample)]
# approved_clones <- unique_genets$sample
# 
# clones_dereplicated <- c(non_clones, approved_clones) # list of sample to keep
# dms_pre_clone_removal <- dms
# remove clones from dms
# dms <- remove.by.list(dms, clones_dereplicated)

# 
# #### final sample number summary ####
# 

# # Clones Removed Site Summary
# clones_removed_site_summary <- dms_pre_clone_removal$meta$analyses %>% as.data.frame()%>%
#   group_by(!!sym(species_col_name), !!sym(site_col_name)) %>%
#   summarize(n_clones_removed = sum(n())) %>%
#   as.data.frame()
# 
# # Merge Site Samples Summary
# site_samples_summary <- merge(original_site_summary, clones_removed_site_summary,
#                               by = c(site_col_name, species_col_name), all.x = TRUE)
# 
# 
# site_samples_summary <- site_samples_summary[,c(3,2,1,4,5)]
# 
# 
# # Calculate total values per unique site_samples_summary[,1] value
# total_summary <- site_samples_summary %>%
#   group_by(species_col_name) %>%
#   summarize(n_original = sum(n_original, na.rm=TRUE), n_no_clones = sum(n_no_clones, na.rm=TRUE)) %>%
#   mutate(pop_large = "Total") %>%
#   mutate(pop = "x") %>%
#   as.data.frame()
# 
# # Combine the original and total summaries
# final_summary <- rbind(site_samples_summary, total_summary)
# 
# final_summary <- final_summary[order(final_summary[,1], final_summary[,3], final_summary[,2]), ]
# final_summary[final_summary$pop=="x","pop"] <- ""
# 
# colnames(final_summary) <- c("Genetic group","Subpopulation",site_col_name, "n (original)","n (no clones)")
# 
# final_summary
# 
# write.xlsx(final_summary, paste0(species,"/outputs/sites_sample_summary.xlsx"), asTable = FALSE, overwrite = TRUE)


#### kinship heatmap
#### Kinship by distance ####

col_fun2 = colorRamp2(c(0,0.2,0.4), c("white", "red","black"))


# kinship_df <- dist_kinship_matrix(dms$gt) %>% as.data.frame(.)
# kinship_df$sample <- rownames(kinship_df)

kinship_df <- kin %>% as.data.frame()
kinship_df$sample <- rownames(kinship_df)


kin_heatmap <- merge(kinship_df, dms$meta$analyses[,c("sample","sp", "lat", species_col_name, site_col_name)],
                   by="sample", all.x=TRUE, all.y=FALSE)
kin_heatmap <- kin_heatmap[match(rownames(kinship_df),kin_heatmap$sample),]
rownames(kin_heatmap) <- kin_heatmap[,"sample"]

kin_heatmap[,"sample"] <- NULL

kin_heatmap[kin_heatmap[,site_col_name]=="no_geo_data",site_col_name] <- NA
kin_heatmap[,site_col_name] <- as.numeric(kin_heatmap[,site_col_name])

kin_heatmap <- kin_heatmap[order(kin_heatmap[,site_col_name]),
                       c(order(kin_heatmap[,site_col_name]),(nrow(kin_heatmap)+1):ncol(kin_heatmap))] #order the table by genet 

#create annotations

site_ann <- HeatmapAnnotation(Location = kin_heatmap[,site_col_name],
                              col = list(Location = site_colours))



sp_ann <- HeatmapAnnotation(Species = kin_heatmap[,species_col_name],
                            col=list(Species=sp_colours),
                            na_col="white",
                            annotation_legend_param = list(labels_gp=gpar(fontface="italic")),
                            annotation_name_gp = gpar(fontsize = 10),
                            annotation_name_side="left")



hma <- Heatmap( as.matrix(kin_heatmap[ , c(1:(nrow(kin_heatmap)))]), 
                col=col_fun2, 
                bottom_annotation=c(site_ann, sp_ann),
                name = "Genetic similarity", #title of legend
                row_names_gp = gpar(fontsize = 2),
                column_names_gp = gpar(fontsize = 2),
                row_names_max_width = unit(15, "cm"),
                border_gp = gpar(col = "black", lty = 1),
                column_order=order(as.numeric(kin_heatmap[,site_col_name])),
                row_order=order(as.numeric(kin_heatmap[,site_col_name]))
)


draw(hma, merge_legend = TRUE)

# Set the file name and parameters
filename <- paste0(species, "/outputs/plots/PLINK_kin_heatmap.pdf")
width <- 30
height <- 20

# Set up the PNG device
pdf(filename, width = width, height = height)
draw(hma)
dev.off()



#### diversity stats ####

# site_stats <- species_site_stats(dms, maf=0.05, pop_var="sp", site_var=site_col_name, missing=0.2)
# big_site_stats <- species_site_stats(dms, maf=0.05, pop_var="sp", site_var="pop_large", missing=0.2)
# gg_stats <- species_site_stats(dms, 0.05, "sp", "sp",missing=0.2)
# gg_separate_stats <- multispecies_stats(dms, 0.05, var=dms$meta$analyses[,"sp"], missing=0.2)

# write.xlsx(site_stats[,c(14,1,15,2,4,5,7,13)], file="PherFitz/outputs/20230822_site_stats_0.05.xlsx", rowNames=TRUE)
# write.xlsx(big_site_stats[,c(14,1,15,2,4,5,7,13)], file="PherFitz/outputs/20230822_pop_large_stats_0.05.xlsx", rowNames=TRUE)
# write.xlsx(gg_stats[,c(14,1,15,2,4,5,7,13)], file="PherFitz/outputs/20230822_sp_stats_0.05.xlsx", rowNames=TRUE)
# write.xlsx(gg_separate_stats[,c(13,1,3,4,6,12)], file="PherFitz/outputs/20230822_gg_separate_stats_0.05.xlsx", rowNames=TRUE)
# 
# 
# dms_pf_0.05_miss20 <- remove.poor.quality.snps(dms, min_repro=0.96, max_missing=0.2) %>%
#   remove.by.maf(., 0.05)
# 
# fitz_allele_list <- make_allele_list(dms_pf_0.05_miss20, dms_pf_0.05_miss20$meta$analyses[,"pop_large_short"], min_af = 0)
# 
# private_total_alleles <- calculate_private_alleles(fitz_allele_list[c(1:3,5:11)])
# private_total_alleles

################################################ PCA ################################################ 

dms_1000 <- remove.loci.randomly(dms, 5000)
gen_d5 <- new("genlight", dms_1000[["gt"]]) #convert df to genlight object for glPca function
gen_pca <- glPca(gen_d5, parallel=TRUE, nf=5) #do pca -- this method allows the input to have NAs 
g_pca_df <- gen_pca[["scores"]] #extract PCs 
g_pca_df2 <- merge(g_pca_df, dms$meta$analyses, by.x=0, by.y="sample", all.y=FALSE, all.x=FALSE) # add metadata 

pcnames <- paste0(colnames(g_pca_df)," (",
                  paste(round(gen_pca[["eig"]][1:5]/sum(gen_pca[["eig"]]) *100, 2)),
                  "%)") #create names for axes


# species PCA
pca_plot_pc12_species <- ggplot(g_pca_df2, aes(x=PC1, y=PC2, colour=!!sym(species_col_name)))+ 
  geom_point()+theme_few()+xlab(pcnames[1])+ylab(pcnames[2])+
  theme(legend.key.size = unit(0, 'lines'),# legend.position = "right",
        legend.text=element_text(face="italic"))+
  scale_colour_manual(values=sp_colours)

ggsave(paste0(species,"/outputs/plots/species_PCA_PC12.png"), plot = pca_plot_pc12_species, width = 20, height = 15, dpi = 600, units = "cm")

# site PCAs

pca_plot_pc12_site <- ggplot(g_pca_df2, 
                             aes(x=PC1, y=PC2,
                                 colour=!!sym(site_col_name)))+ 
  geom_point()+theme_few()+xlab(pcnames[1])+ylab(pcnames[2])+
  theme(legend.key.size = unit(0, 'lines'))+
  scale_colour_manual(values=site_colours)+
  geom_text_repel(data= g_pca_df2, mapping= aes(x=PC1, y=PC2,label=!!sym(site_col_name)),colour="black",
                  size=2, max.overlaps=20, show.legend=FALSE,force_pull = 2, box.padding = 0.25, segment.size=0.1, min.segment.length = 0)

pca_plot_pc23_site <- ggplot(g_pca_df2, 
                             aes(x=PC3, y=PC2,
                                 colour=!!sym(site_col_name)))+ 
  geom_point()+theme_few()+xlab(pcnames[3])+ylab(pcnames[2])+
  theme(legend.key.size = unit(0, 'lines'))+
  scale_colour_manual(values=site_colours)+
  geom_text_repel(data= g_pca_df2, mapping= aes(x=PC3, y=PC2,label=!!sym(site_col_name)),colour="black",
                  size=2, max.overlaps=20, show.legend=FALSE,force_pull = 2, box.padding = 0.25, segment.size=0.1, min.segment.length = 0)

pca_plot_pc34_site <- ggplot(g_pca_df2, 
                             aes(x=PC3, y=PC4,
                                 colour=!!sym(site_col_name)))+ 
  geom_point()+theme_few()+xlab(pcnames[3])+ylab(pcnames[4])+
  theme(legend.key.size = unit(0, 'lines'))+
  scale_colour_manual(values=site_colours)+
  geom_text_repel(data= g_pca_df2, mapping= aes(x=PC3, y=PC4,label=!!sym(site_col_name)),colour="black",
                  size=2, max.overlaps=20, show.legend=FALSE,force_pull = 2, box.padding = 0.25, segment.size=0.1, min.segment.length = 0)


combined_site_pca <- ggarrange(pca_plot_pc12_site, pca_plot_pc23_site, pca_plot_pc34_site, ncol=3, common.legend = TRUE, legend="right")
# combined_site_pca

ggsave(paste0(species,"/outputs/plots/site_PCA_all.png"), plot = combined_site_pca, width = 30, height = 10, dpi = 600, units = "cm")
ggsave(paste0(species,"/outputs/plots/site_PCA_PC12.png"), plot = pca_plot_pc12_site, width = 20, height = 15, dpi = 600, units = "cm")

# latitude PCAs

pca_plot_pc12_lat <- ggplot(g_pca_df2, aes(x=PC1, y=PC2, colour=as.numeric(lat)))+ 
  labs(color="Latitude")+
  geom_point()+theme_few()+ xlab(pcnames[1])+ylab(pcnames[2])+
  scale_color_gradient(high = "red",low = "blue", na.value = "grey30")

pca_plot_pc23_lat <- ggplot(g_pca_df2, aes(x=PC3, y=PC2, colour=as.numeric(lat)))+ 
  labs(color="Latitude")+
  geom_point()+theme_few()+xlab(pcnames[3])+ylab(pcnames[2])+
  scale_color_gradient(high = "red",low = "blue", na.value = "grey30")

pca_plot_pc34_lat <- ggplot(g_pca_df2, aes(x=PC3, y=PC4, colour=as.numeric(lat)))+ 
  labs(color="Latitude")+
  geom_point()+theme_few()+xlab(pcnames[3])+ylab(pcnames[4])+
  scale_color_gradient(high = "red",low = "blue", na.value = "grey30")

combined_latitude_pca <- ggarrange(pca_plot_pc12_lat, pca_plot_pc23_lat, pca_plot_pc34_lat, ncol=3, common.legend = TRUE, legend="right")
combined_latitude_pca

ggsave(paste0(species,"/outputs/plots/latitude_PCA_all.png"), plot = combined_latitude_pca, width = 30, height = 10, dpi = 600, units = "cm")

#### FST ####



# calculate FST and geodist
gds_file <- dart2gds(dms_no_n1_sites, RandRbase, species, dataset)
pFst      <- population.pw.Fst(dms_no_n1_sites, dms_no_n1_sites$meta$site, RandRbase,species,dataset, maf_val=0.05, miss_val=0.2) #calculates genetic distance 
pS        <- population.pw.spatial.dist(dms_no_n1_sites, dms_no_n1_sites$meta$site) #calculates geographic distance between populations


####plot IBD plot

# Make self comparisons NA
diag(pFst$Fst) <- NA
diag(pS$S) <- NA

#Mantel test 
man <- mantel(xdis = pS$S, ydis = pFst$Fst, permutations = 10000, na.rm = TRUE) #mantel test, finds if matrices are signficantly similar
man

# mantel plot
Fst_sig <- cbind(melt(pS$S), unlist(as.list(pFst$Fst)))
colnames(Fst_sig)[3] <- "Geo_dist"
colnames(Fst_sig)[4] <- "Fst"
Fst_sig$Geo_dist2 <-Fst_sig$Geo_dist/1000 

# adding metadata for sites
Fst_sig2 <- merge(Fst_sig, distinct(original_site_summary[,c(site_col_name,species_col_name)]), by.x="Var1", by.y=site_col_name, all.y=FALSE)
Fst_sig2 <- merge(Fst_sig2, distinct(original_site_summary[,c(site_col_name,species_col_name)]), by.x="Var2", by.y=site_col_name, all.y=FALSE)
Fst_sig2$same_sp <- ifelse(Fst_sig2[,6]== Fst_sig2[,7], paste("Within", species_col_name), paste("Between", species_col_name))

fstp1<- ggplot(Fst_sig2, aes(x= Geo_dist2, y=Fst, color=same_sp))+geom_point(size=1, alpha=0.3)+
  labs(x="Distance (km)", y="FST", colour="Comparison")+
  # facet_zoom(x=Geo_dist2<2, zoom.size=1)+
  geom_hline(yintercept = 0.3, color="black", linetype="dotted")+
  theme_few()+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), legend.position="bottom")+
  labs(title = paste("Mantel statistic r is", round(man$statistic, 3), ", P =", round(man$signif, 5)))+ theme(plot.title = element_text(size=10))

fstp1

ggsave(paste0(species,"/outputs/plots/manning_fst.png"),
       fstp1, width = 15, height = 10, units = "cm", dpi=600)


# Make heatmaps
# geo dist
geo_d <-pS$S #this is a square matrix
mat <- geo_d/1000 # convert to km 

#FST
mat2 <-pFst$Fst
mat2 <- merge(mat2, original_site_summary, by.x=0, by.y=site_col_name, all.y=FALSE) #add aggregated df to mat2 (fst)
rownames(mat2) <- mat2$Row.names

mat2$Row.names <- NULL
mat2 <- mat2[match(colnames(mat2)[1:nrow(mat2)],rownames(mat2)),]

order_hm <- Heatmap(mat,
                    cluster_rows = TRUE,
                    cluster_columns = TRUE)
od <- colnames(mat)[column_order(order_hm)]

mat = mat[od, od]
mat2 = mat2[od, c(od,site_col_name)]

# specify fst heatmap colours 
gene_col <-  colorRamp2(c(0,0.5,1), c("#8DD3C7", "white", "#FB8072"))


#specify geo heatmap colours
palette <-  colorRamp2(c(0, max(mat, na.rm=TRUE)), c("white", "#80B1D3"))


row_sp_ann <- rowAnnotation(Subpopulation = mat2[,species_col_name],
                                       col=list(Subpopulation=sp_colours),
                                       na_col="white",
                                       annotation_legend_param = list(labels_gp=gpar(fontsize=6),#fontface="italic",
                                                                      title_gp=gpar(fontsize=8)),
                                       annotation_name_gp = gpar(fontsize = 0),
                                       annotation_name_side="top")

bottom_sp_ann <- HeatmapAnnotation(Subpopulation = mat2[,species_col_name], 
                                   col = list(Subpopulation = sp_colours),
                                              annotation_name_gp = gpar(fontsize = 0),
                                              show_legend = FALSE,
                                              annotation_name_side="right",
                                              na_col = "white")

geo <- Heatmap(mat,rect_gp = gpar(type = "none"),
               width = nrow(mat)*unit(4, "mm"),
               height = nrow(mat)*unit(4, "mm"),
               col=palette,na_col="white",
               bottom_annotation = bottom_sp_ann,
               column_names_gp = gpar(fontsize = 6),
               cluster_rows = FALSE,
               cluster_columns = FALSE,
               name="Distance (km)",
               heatmap_legend_param = list(title_gp = gpar(fontsize = 8),
                                           labels_gp = gpar(fontsize = 6)),
               # cluster_rows = TRUE, 
               # cluster_columns = TRUE,
               cell_fun = function(j, i, x, y, w, h, fill) {
                 if(i >= j) {
                   grid.rect(x, y, w, h, gp = gpar(fill = fill, col = fill))
                 }
               }
)

# make fst heatmap
gene <- Heatmap(as.matrix(mat2[,1:nrow(mat2)]), rect_gp = gpar(type = "none"),
                width = nrow(mat2)*unit(4, "mm"),
                height = nrow(mat2)*unit(4, "mm"),
                right_annotation = row_sp_ann,
                col=gene_col,na_col="grey",
                row_names_gp = gpar(fontsize = 6),
                column_names_gp = gpar(fontsize = 0),
                border_gp = gpar(col = "black", lty = 1),
                name="FST",
                cluster_rows = FALSE,
                cluster_columns = FALSE,
                heatmap_legend_param = list(title_gp = gpar(fontsize = 8),
                                            labels_gp = gpar(fontsize = 6)),
                cell_fun = function(j, i, x, y, w, h, fill) {
                  if(i <= j) {
                    grid.rect(x, y, w, h, gp = gpar(fill = fill, col = fill))
                    grid.text(sprintf("%.2f", mat2[,1:nrow(mat2)][i, j]), x, y, gp = gpar(fontsize = 4))
                  }
                })

gene_width <- nrow(mat2)*unit(4, "mm")

draw(geo + gene, ht_gap = -gene_width)

# Set the file name and parameters
filename <- paste0(species, "/outputs/plots/fst_plot_overlay.pdf")
width <- (((nrow(mat2)*4)/10) +8)*0.394
height <- (((nrow(mat2)*4)/10)+5)*0.394

# Set up the PNG device
pdf(filename, width = width, height = height)

# Draw the plot
draw(geo + gene, ht_gap = -gene_width)

# Turn off the PNG device
dev.off()


write.xlsx(list(geo_dist_km=mat, fst=mat2), 
            paste0(species,"/outputs/tables/geodist_FST_by_",site_col_name,".xlsx"),rowNames = TRUE)

#### Visualise splitstree ####

splitstree(dist(dms$gt), paste0(species,'/outputs/r_files/nexus_file_for_R.nex'))

#need to open and save the file in Splitstree app for it to open here, IDK why
Nnet <- phangorn::read.nexus.networx(paste0(species,'/outputs/r_files/nexus_file_for_R.nex'))

x <- data.frame(x=Nnet$.plot$vertices[,1], y=Nnet$.plot$vertices[,2], 
                sample=rep(NA, nrow(Nnet$.plot$vertices)))

x[Nnet$translate$node,"sample"] <- Nnet$translate$label
x <- merge(x, dms$meta$analyses, by="sample", all.x=TRUE, all.y=FALSE)

net_x_axis <- max(x$x)-min(x$x)
net_y_axis <- max(x$y)-min(x$y)

Nnet$translate$label <-  x[match(Nnet$tip.label, x$sample), site_col_name] %>% .[1:length(Nnet$tip.label)]



splitstree_plot_species <- ggplot(Nnet, mapping = aes_(~x, ~y), layout = "slanted", mrsd = NULL, 
                          as.Date = FALSE, yscale = "none", yscale_mapping = NULL, 
                          ladderize = FALSE, right = FALSE, branch.length = "branch.length", 
                          ndigits = NULL)+
  geom_splitnet(layout = "slanted", size=0.2)+
  geom_point(data=x, aes(x, y, colour=!!sym(species_col_name)))+
  scale_colour_manual(values=sp_colours, na.translate=FALSE,
                      guide = guide_legend(species_col_name))+
  # geom_tiplab2(size=2, hjust=-0.2)+
  theme_void()+
  expand_limits(x=c(min(x$x)-0.01*net_x_axis, max(x$x)+0.01*net_x_axis),
                y=c(min(x$y)-0.01*net_y_axis, max(x$y)+0.01*net_y_axis))+
  theme(legend.text = element_text(face="italic"), legend.position = "top")+coord_fixed()

splitstree_plot_species

## site splitstree
Nnet <- phangorn::read.nexus.networx(paste0(species,'/outputs/r_files/nexus_file_for_R.nex'))

x <- data.frame(x=Nnet$.plot$vertices[,1], y=Nnet$.plot$vertices[,2], 
                sample=rep(NA, nrow(Nnet$.plot$vertices)))

x[Nnet$translate$node,"sample"] <- Nnet$translate$label
x <- merge(x, dms$meta$analyses, by="sample", all.x=TRUE, all.y=FALSE)

net_x_axis <- max(x$x)-min(x$x)
net_y_axis <- max(x$y)-min(x$y)

Nnet$translate$label <-  x[match(Nnet$tip.label, x$sample), site_col_name] %>% .[1:length(Nnet$tip.label)]



splitstree_plot_site <- ggplot(Nnet, mapping = aes_(~x, ~y), layout = "slanted", mrsd = NULL, 
                                  as.Date = FALSE, yscale = "none", yscale_mapping = NULL, 
                                  ladderize = FALSE, right = FALSE, branch.length = "branch.length", 
                                  ndigits = NULL)+
  geom_splitnet(layout = "slanted", size=0.2)+
  geom_point(data=x, aes(x, y, colour=!!sym(site_col_name)))+
  scale_colour_manual(values=site_colours, na.translate=FALSE,
                      guide = guide_legend(site_col_name))+
  geom_tiplab2(size=2, hjust=-3)+
  theme_void()+
  expand_limits(x=c(min(x$x)-0.01*net_x_axis, max(x$x)+0.01*net_x_axis),
                y=c(min(x$y)-0.01*net_y_axis, max(x$y)+0.01*net_y_axis))+
  theme(legend.text = element_text(face="italic"), legend.position = "none")+coord_fixed()

splitstree_plot_site


ggsave(paste0(species,"/outputs/plots/small_splitstree.png"), plot = splitstree_plot_site, width = 20, height = 30, dpi = 600, units = "cm")


# map by species

# TO DO 
# LEA PLOTYS WITH MAPS
# SITE MAP
# DIVERSITY STATS

########################################### LEA ########################################
kvalrange <- 2:8

##check for LEA FOLDER
lea_project <- paste0(maindir,RandRbase,species,"/popgen/",treatment,"/lea/",species,"_",dataset,".snmfProject")

if(!file.exists(lea_project)){
  nd_lea <- dart2lea(dms_no_n1_sites, RandRbase, species, dataset)
  snmf1=snmf(nd_lea, K=kvalrange, entropy = TRUE, repetitions = 1, project = "new")
  plot(snmf1, lwd = 6, col = "red", pch=1)
  # LEA_plots(dms_no_n1_sites, outputloc, nd_lea,treatment, dataset, species)
}else{
  print("LEA project already exists")
}
  
#load whole project
snmf_project <- load.snmfProject(lea_project)

## entropy 
entropy <- t(summary(snmf_project)$crossEntropy) %>% as.data.frame()
entropy_plot <- ggplot(entropy, aes(x=kvalrange, y=mean))+geom_point(colour="red")+theme_few()+
  labs(x="K", y="Mean ncross entropy")+
  theme(axis.text = element_text(size=6), axis.title = element_text(size=8),
        legend.position="none")


scatterpie_plots <- list()
admix_bar_plots <- list()
admix_bar_plots_mini <- list()
map_mini <- list()

#for each k value
for (kval in kvalrange){
  ce           <- cross.entropy(snmf_project, K = kval)
  Rbest        <- which.min(ce) # with the lowest cross entropy criterion
  
  qdf <- Q(snmf_project, K=kval, run=Rbest) # get admixture coefficients (Q) for each sample
  qdf2 <- as.data.frame(qdf)#, samples=dms_no_n1_sites$sample_names) # add the metadata
  qdf2$sample <- as.vector(dms_no_n1_sites$sample_names)

  qdf3  <- merge(qdf2, dms_no_n1_sites$meta$analyses[,c("sample",site_col_name, "lat", "long")], by="sample", all.x=TRUE, all.y=FALSE)
  colnames(qdf3)[which(colnames(qdf3)==site_col_name)]<- "site"
  
  qdf4 <- qdf3
  
  qdf4$sample <- NULL
  for (i in 1:kval){
    qdf4[,i] <- as.numeric(qdf4[,i])
  }
  qdf4[,"lat"] <- as.numeric(qdf4[,"lat"])
  qdf4[,"long"] <- as.numeric(qdf4[,"long"])
  
  agg_qdf <- aggregate(. ~ site, data = qdf4, FUN = mean)
  
  
  scatter_map <- ggplot(ozmaps::abs_ste) + geom_sf(fill="grey96", colour="grey28") +
  coord_sf(xlim = divxlims, ylim = divylims) + labs(y=element_blank(), x=element_blank(), fill="Source\npopulation")+
  geom_scatterpie(mapping=aes(x=long, y=lat, group =site, r = diff(divxlims)/20),data =agg_qdf,
                    cols=colnames(agg_qdf)[2:(kval+1)],  alpha=1, size=0.1, colour="black", na.rm=TRUE)+theme_few()+
    theme_few()+theme(axis.text.x = element_text(angle=90, size=6),axis.text.y=element_text(size=6), legend.position = "none")+
    ggsn::scalebar(agg_qdf, dist = round(diff(divxlims)*20,-1), dist_unit = "km", location = "bottomright", 
                   st.bottom = F, st.size = 2, st.dist = 0.02,border.size =0.5,
                   transform = TRUE, model = "WGS84", height = 0.01)+
    labs(title=paste("K = ",kval))
  
  # make admix plot
  qdf_long <- pivot_longer(qdf3, cols=2:(kval+1), names_to="population", values_to="Q") 
  
  # # Order the data frame based on the index
  # qdf_long <- qdf_long[order(match(qdf_long$site, site_order)), ]
  # qdf_long$sample <- factor(qdf_long$sample, levels = unique(qdf_long$sample))
  # 
  # 
  admix_plot <- ggplot(qdf_long, 
                    aes(x=sample, #, labels=NULL),
                        y=Q, fill=population))+
    geom_bar(position="stack", stat="identity")+
    theme_few()+
    labs(y="Admixture\ncoefficient (Q)", x=element_blank(), fill="Source\npopulation")+
    facet_grid(~factor(site, levels=site_order), scales = "free_x", space = "free_x")+
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1, size=3),
          strip.text.x = element_text(size = 6), strip.background = element_blank(), 
          axis.title.y = element_text(size=8),
          legend.position="none")+
    scale_y_continuous(limits = c(0,1.001), expand=c(0,0))+
    theme(strip.text.x = element_text(angle = 90, size=6), panel.spacing = unit(0.07, "lines"))+
    labs(title=paste("K = ",kval))
  
  
  admix_plot_mini <- ggplot(qdf_long, 
                       aes(x=Q,
                           y=sample, fill=population))+
    geom_bar(position="stack", stat="identity", show.legend = FALSE)+
    theme_void()
  

  scatterpie_plots[[kval]] <- scatter_map
  admix_bar_plots[[kval]] <- admix_plot
  admix_bar_plots_mini[[kval]] <- admix_plot_mini
  
  # map_mini[[kval]] <- ggarrange(scatter_map+theme(plot.margin = unit(c(0,0,0,0), 'lines')),
  #                               admix_plot_mini+theme(plot.margin = unit(c(0,0,0,0), 'lines')), align="hv", ncol=2, widths=c(3,2))
}


# Extract the plots based on the indices
scatterpie_plots_to_arrange <- lapply(kvalrange, function(i) scatterpie_plots[[i]])
# Arrange the plots using ggarrange
arranged_scatterpie_plots <- ggarrange(plotlist = scatterpie_plots_to_arrange, ncol = 4, nrow = 2)
arranged_scatterpie_plots


admix_plots_to_arrange <- lapply(kvalrange, function(i) admix_bar_plots[[i]])
# arranged_admix_plots <- ggarrange(plotlist = admix_plots_to_arrange, ncol = 1, nrow = 8, common.legend = TRUE, 
#                                   legend= "none")


# Create a PDF file to save the plots
max_plots_per_page <- 5
pdf(paste0(species,"/outputs/plots/admix_barplots.pdf"),width = 8.3, height = 11.7)
# Loop through the list of ggplots and print them to the PDF
for (i in seq(min(kvalrange), length(admix_bar_plots), by = max_plots_per_page)) {
  end <- min(i + max_plots_per_page - 1, length(admix_bar_plots))
  plots_to_print <- admix_bar_plots[i:end]
  grid.arrange(grobs = plots_to_print, ncol = 1, nrow=5)
}
dev.off()

# Create a PDF file to save the plots
pdf(paste0(species,"/outputs/plots/scatterpie_map.pdf"),width = 8, height = 8.3)

# Loop through the list of ggplots and print them to the PDF
for (i in seq(min(kvalrange), length(scatterpie_plots), by = 8)) {
  end <- min(i + 8 - 1, length(scatterpie_plots))
  plots_to_print <- scatterpie_plots[i:end]
  grid.arrange(grobs = plots_to_print, ncol = 4, nrow=2)
}

# Close the PDF file
dev.off()


########################################### MAP ########################################


plain_map <- ggplot(ozmaps::abs_ste) + geom_sf(fill="white", colour="grey28") +theme_few()+
  coord_sf(xlim = divxlims, ylim = divylims) + labs(y=element_blank(), x=element_blank())+
  geom_point(data=site_stats_merged, mapping=aes(x=long, y=lat, fill=!!sym(site_col_name)), shape=21, size=2)+ #, shape=!!sym(site_col_name)
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1), legend.position = "none")+
  scale_fill_manual(values=site_colours)+
  # scale_shape_manual(values=site_shapes)+
  geom_text_repel(data=site_stats_merged, mapping=aes(x=long, y=lat, size=fis, label=!!sym(site_col_name)),colour="black",
                  size=3, max.overlaps=20, show.legend=FALSE,force_pull = 2, box.padding = 0.25, segment.size=0.1, min.segment.length = 0)+
  ggsn::scalebar(agg_qdf, dist = round(diff(divxlims)*20,-1), dist_unit = "km", location = "bottomright", 
                 st.bottom = F, st.size = 3, st.dist = 0.02,border.size =0.5,
                 transform = TRUE, model = "WGS84", height = 0.01)
plain_map


#######################################DIVERSITY######################################
site_stats <- species_site_stats(dms_1000, maf=0.05, pop_var=species_col_name, site_var=site_col_name, missing=0.2)
site_stats_merged <- merge(site_stats, original_site_summary[,c(1:2,4:5)], by=site_col_name)

# Find the maximum of the two size variables
het_range <- range(min(site_stats_merged[,c('obs_het', 'exp_het')]), max(site_stats_merged[,c('obs_het', 'exp_het')]))


write.xlsx(site_stats_merged, 
            paste0(species,"/outputs/tables/statistics_",site_col_name,"_by_",species_col_name,".xlsx"), rowNames = FALSE)


ho_map <- ggplot(ozmaps::abs_ste) + geom_sf(fill = "grey96", colour = "grey28") +
  coord_sf(xlim = divxlims, ylim = divylims) + labs(y = element_blank(), x = element_blank()) +
  geom_point(data = site_stats_merged, mapping = aes(x = long, y = lat, size = obs_het), alpha = 0.3, color = "red") +
  geom_point(data=site_stats_merged, mapping=aes(x=long, y=lat),size=0.1)+
  theme_few() +
  theme(legend.position = "bottom", legend.direction = "vertical", 
        axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
  labs(title = "HO", size="HO")+
  scale_size_continuous(limits = het_range)+
  geom_text_repel(data=site_stats_merged, mapping=aes(x=long, y=lat, size=fis, label=!!sym(site_col_name)),colour="black",
                  size=2, max.overlaps=20, show.legend=FALSE,force_pull = 2, box.padding = 0.25, segment.size=0.1, min.segment.length = 0)

he_map <- ggplot(ozmaps::abs_ste) + geom_sf(fill = "grey96", colour = "grey28") +
  coord_sf(xlim = divxlims, ylim = divylims) + labs(y = element_blank(), x = element_blank()) +
  geom_point(data = site_stats_merged, mapping = aes(x = long, y = lat, size =exp_het), alpha = 0.3, color = "red") +
  geom_point(data=site_stats_merged, mapping=aes(x=long, y=lat),size=0.1)+
  theme_few() +
  theme(legend.position = "bottom", legend.direction = "vertical",
        axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
  labs(title = "HE", size="HE")+
  scale_size_continuous(limits = het_range)+
  geom_text_repel(data=site_stats_merged, mapping=aes(x=long, y=lat, size=fis, label=!!sym(site_col_name)),colour="black",
                  size=2, max.overlaps=20, show.legend=FALSE,force_pull = 2, box.padding = 0.25, segment.size=0.1, min.segment.length = 0)

fis_map <- ggplot(ozmaps::abs_ste) + geom_sf(fill="grey96", colour="grey28") +
  coord_sf(xlim = divxlims, ylim = divylims) + labs(y=element_blank(), x=element_blank())+
  geom_point(data=site_stats_merged, mapping=aes(x=long, y=lat, size=fis, color=fis), alpha=0.5)+
  theme_few()+
  scale_color_gradient2(high = "red",mid="white", midpoint = 0, low = "blue", na.value = "grey30")+
  geom_point(data=site_stats_merged, mapping=aes(x=long, y=lat),size=0.1)+
  theme(legend.position = "bottom", legend.direction = "vertical",
        axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))+
  labs(title="FIS")+
  geom_text_repel(data=site_stats_merged, mapping=aes(x=long, y=lat, size=fis, label=!!sym(site_col_name)),colour="black",
                  size=2, max.overlaps=20, show.legend=FALSE,force_pull = 2, box.padding = 0.25, segment.size=0.1, min.segment.length = 0)




combined_stats_plot <- ( ho_map | he_map | fis_map ) / ncol(3)


